baseurl = "https://mateuszgrzelak.github.io"
title = "Mateusz Grzelak"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 10 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/background.jpg"
  title = "Blog about cyber security"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "Mateusz Grzelak Blog"
  keyword = "Grzelak, Security, Raspberry, Pi"
 
  # Sidebar settings
  sidebar_about_description = "Father, Husband, Skier, Cyclist, and, oh yeah, Software Developer"
  # sidebar_avatar = "images/MeAtJackson.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  # image_404 = "images/404-bg.jpg"
  # title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "rich.youngkin@gmail.com"
  linkedin       = "https://www.linkedin.com/in/richard-youngkin-0749763"
  github         = "https://github.com/youngkin"
  medium         = "https://medium.com/@RichYoungkin"
  stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  reddit         = "https://www.reddit.com/user/elevation5280"